services:
  - type: web
    name: restaurant-system
    env: python
    buildCommand: rm -rf .venv && pip install --no-cache-dir -r requirements-prod.txt
    startCommand: python start_server.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PORT
        value: 8000
